// Mock data for the Draft Room feature.
// MOCK_PLAYERS: ~100 NFL players across 6 positions and 12 NFL teams.
// MOCK_TEAMS: 12 fantasy teams with id, name, and initials.

export const MOCK_PLAYERS = [
  // QBs (~15)
  { id: 'p_001', name: 'Patrick Mahomes', position: 'QB', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC', touchdowns: 38, passYards: 5250, rushYards: 358, recYards: 0 },
  { id: 'p_002', name: 'Josh Allen', position: 'QB', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF', touchdowns: 40, passYards: 4906, rushYards: 531, recYards: 0 },
  { id: 'p_003', name: 'Lamar Jackson', position: 'QB', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL', touchdowns: 39, passYards: 3678, rushYards: 821, recYards: 0 },
  { id: 'p_004', name: 'Joe Burrow', position: 'QB', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN', touchdowns: 35, passYards: 4641, rushYards: 213, recYards: 0 },
  { id: 'p_005', name: 'Jalen Hurts', position: 'QB', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI', touchdowns: 43, passYards: 3858, rushYards: 605, recYards: 0 },
  { id: 'p_006', name: 'Tua Tagovailoa', position: 'QB', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA', touchdowns: 29, passYards: 4624, rushYards: 127, recYards: 0 },
  { id: 'p_007', name: 'Dak Prescott', position: 'QB', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL', touchdowns: 36, passYards: 4516, rushYards: 242, recYards: 0 },
  { id: 'p_008', name: 'Justin Herbert', position: 'QB', nflTeam: 'Los Angeles Chargers', nflTeamAbbr: 'LAC', touchdowns: 31, passYards: 4739, rushYards: 157, recYards: 0 },
  { id: 'p_009', name: 'Trevor Lawrence', position: 'QB', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX', touchdowns: 27, passYards: 4016, rushYards: 285, recYards: 0 },
  { id: 'p_010', name: 'Anthony Richardson', position: 'QB', nflTeam: 'Indianapolis Colts', nflTeamAbbr: 'IND', touchdowns: 25, passYards: 3512, rushYards: 647, recYards: 0 },
  { id: 'p_011', name: 'Sam Darnold', position: 'QB', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN', touchdowns: 26, passYards: 3831, rushYards: 198, recYards: 0 },
  { id: 'p_012', name: 'Jordan Love', position: 'QB', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB', touchdowns: 32, passYards: 4159, rushYards: 234, recYards: 0 },
  { id: 'p_013', name: 'C.J. Stroud', position: 'QB', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU', touchdowns: 33, passYards: 4108, rushYards: 261, recYards: 0 },
  { id: 'p_014', name: 'Caleb Williams', position: 'QB', nflTeam: 'Chicago Bears', nflTeamAbbr: 'CHI', touchdowns: 28, passYards: 3743, rushYards: 312, recYards: 0 },
  { id: 'p_015', name: 'Jayden Daniels', position: 'QB', nflTeam: 'Washington Commanders', nflTeamAbbr: 'WAS', touchdowns: 30, passYards: 3824, rushYards: 594, recYards: 0 },

  // RBs (~22)
  { id: 'p_016', name: 'Christian McCaffrey', position: 'RB', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF', touchdowns: 17, passYards: 0, rushYards: 1459, recYards: 564 },
  { id: 'p_017', name: 'Saquon Barkley', position: 'RB', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI', touchdowns: 15, passYards: 0, rushYards: 1838, recYards: 278 },
  { id: 'p_018', name: 'Derrick Henry', position: 'RB', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL', touchdowns: 16, passYards: 0, rushYards: 1921, recYards: 212 },
  { id: 'p_019', name: 'Josh Jacobs', position: 'RB', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB', touchdowns: 11, passYards: 0, rushYards: 1329, recYards: 391 },
  { id: 'p_020', name: 'Tony Pollard', position: 'RB', nflTeam: 'Tennessee Titans', nflTeamAbbr: 'TEN', touchdowns: 8, passYards: 0, rushYards: 1009, recYards: 467 },
  { id: 'p_021', name: 'Rhamondre Stevenson', position: 'RB', nflTeam: 'New England Patriots', nflTeamAbbr: 'NE', touchdowns: 9, passYards: 0, rushYards: 1143, recYards: 332 },
  { id: 'p_022', name: 'Travis Etienne', position: 'RB', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX', touchdowns: 10, passYards: 0, rushYards: 1182, recYards: 419 },
  { id: 'p_023', name: 'Jonathan Taylor', position: 'RB', nflTeam: 'Indianapolis Colts', nflTeamAbbr: 'IND', touchdowns: 13, passYards: 0, rushYards: 1412, recYards: 289 },
  { id: 'p_024', name: "De'Von Achane", position: 'RB', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA', touchdowns: 14, passYards: 0, rushYards: 1394, recYards: 543 },
  { id: 'p_025', name: 'Isiah Pacheco', position: 'RB', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC', touchdowns: 9, passYards: 0, rushYards: 1203, recYards: 247 },
  { id: 'p_026', name: 'Brian Robinson Jr.', position: 'RB', nflTeam: 'Washington Commanders', nflTeamAbbr: 'WAS', touchdowns: 8, passYards: 0, rushYards: 1048, recYards: 215 },
  { id: 'p_027', name: 'Jahmyr Gibbs', position: 'RB', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET', touchdowns: 12, passYards: 0, rushYards: 1267, recYards: 516 },
  { id: 'p_028', name: 'David Montgomery', position: 'RB', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET', touchdowns: 13, passYards: 0, rushYards: 1149, recYards: 308 },
  { id: 'p_029', name: 'Kyren Williams', position: 'RB', nflTeam: 'Los Angeles Rams', nflTeamAbbr: 'LAR', touchdowns: 11, passYards: 0, rushYards: 1219, recYards: 376 },
  { id: 'p_030', name: 'Aaron Jones', position: 'RB', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN', touchdowns: 10, passYards: 0, rushYards: 978, recYards: 425 },
  { id: 'p_031', name: 'James Cook', position: 'RB', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF', touchdowns: 12, passYards: 0, rushYards: 1122, recYards: 489 },
  { id: 'p_032', name: 'Breece Hall', position: 'RB', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ', touchdowns: 11, passYards: 0, rushYards: 1337, recYards: 512 },
  { id: 'p_033', name: 'Najee Harris', position: 'RB', nflTeam: 'Pittsburgh Steelers', nflTeamAbbr: 'PIT', touchdowns: 8, passYards: 0, rushYards: 1035, recYards: 294 },
  { id: 'p_034', name: 'Joe Mixon', position: 'RB', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU', touchdowns: 13, passYards: 0, rushYards: 1219, recYards: 356 },
  { id: 'p_035', name: 'Alvin Kamara', position: 'RB', nflTeam: 'New Orleans Saints', nflTeamAbbr: 'NO', touchdowns: 10, passYards: 0, rushYards: 897, recYards: 567 },
  { id: 'p_036', name: 'Nick Chubb', position: 'RB', nflTeam: 'Cleveland Browns', nflTeamAbbr: 'CLE', touchdowns: 9, passYards: 0, rushYards: 1176, recYards: 198 },
  { id: 'p_037', name: 'Bijan Robinson', position: 'RB', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL', touchdowns: 14, passYards: 0, rushYards: 1413, recYards: 481 },

  // WRs (~28)
  { id: 'p_038', name: 'Tyreek Hill', position: 'WR', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA', touchdowns: 13, passYards: 0, rushYards: 52, recYards: 1799 },
  { id: 'p_039', name: 'Justin Jefferson', position: 'WR', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN', touchdowns: 12, passYards: 0, rushYards: 21, recYards: 1714 },
  { id: 'p_040', name: 'CeeDee Lamb', position: 'WR', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL', touchdowns: 12, passYards: 0, rushYards: 38, recYards: 1749 },
  { id: 'p_041', name: 'Davante Adams', position: 'WR', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ', touchdowns: 11, passYards: 0, rushYards: 14, recYards: 1144 },
  { id: 'p_042', name: 'Stefon Diggs', position: 'WR', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU', touchdowns: 9, passYards: 0, rushYards: 18, recYards: 1183 },
  { id: 'p_043', name: 'A.J. Brown', position: 'WR', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI', touchdowns: 11, passYards: 0, rushYards: 31, recYards: 1456 },
  { id: 'p_044', name: "Ja'Marr Chase", position: 'WR', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN', touchdowns: 13, passYards: 0, rushYards: 26, recYards: 1607 },
  { id: 'p_045', name: 'DeVonta Smith', position: 'WR', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI', touchdowns: 8, passYards: 0, rushYards: 12, recYards: 1066 },
  { id: 'p_046', name: 'Amon-Ra St. Brown', position: 'WR', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET', touchdowns: 10, passYards: 0, rushYards: 43, recYards: 1515 },
  { id: 'p_047', name: 'Puka Nacua', position: 'WR', nflTeam: 'Los Angeles Rams', nflTeamAbbr: 'LAR', touchdowns: 7, passYards: 0, rushYards: 9, recYards: 1486 },
  { id: 'p_048', name: 'Keenan Allen', position: 'WR', nflTeam: 'Chicago Bears', nflTeamAbbr: 'CHI', touchdowns: 8, passYards: 0, rushYards: 6, recYards: 1139 },
  { id: 'p_049', name: 'Tee Higgins', position: 'WR', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN', touchdowns: 9, passYards: 0, rushYards: 15, recYards: 1091 },
  { id: 'p_050', name: 'Mike Evans', position: 'WR', nflTeam: 'Tampa Bay Buccaneers', nflTeamAbbr: 'TB', touchdowns: 13, passYards: 0, rushYards: 8, recYards: 1255 },
  { id: 'p_051', name: 'Chris Olave', position: 'WR', nflTeam: 'New Orleans Saints', nflTeamAbbr: 'NO', touchdowns: 7, passYards: 0, rushYards: 11, recYards: 1098 },
  { id: 'p_052', name: 'Deebo Samuel', position: 'WR', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF', touchdowns: 9, passYards: 0, rushYards: 89, recYards: 892 },
  { id: 'p_053', name: 'Brandon Aiyuk', position: 'WR', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF', touchdowns: 10, passYards: 0, rushYards: 17, recYards: 1342 },
  { id: 'p_054', name: 'Christian Watson', position: 'WR', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB', touchdowns: 8, passYards: 0, rushYards: 22, recYards: 934 },
  { id: 'p_055', name: 'Garrett Wilson', position: 'WR', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ', touchdowns: 8, passYards: 0, rushYards: 19, recYards: 1042 },
  { id: 'p_056', name: 'Rashee Rice', position: 'WR', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC', touchdowns: 10, passYards: 0, rushYards: 27, recYards: 938 },
  { id: 'p_057', name: 'Drake London', position: 'WR', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL', touchdowns: 7, passYards: 0, rushYards: 14, recYards: 1012 },
  { id: 'p_058', name: 'Zay Jones', position: 'WR', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX', touchdowns: 6, passYards: 0, rushYards: 5, recYards: 753 },
  { id: 'p_059', name: 'Courtland Sutton', position: 'WR', nflTeam: 'Denver Broncos', nflTeamAbbr: 'DEN', touchdowns: 8, passYards: 0, rushYards: 7, recYards: 1032 },
  { id: 'p_060', name: 'Diontae Johnson', position: 'WR', nflTeam: 'Carolina Panthers', nflTeamAbbr: 'CAR', touchdowns: 6, passYards: 0, rushYards: 3, recYards: 784 },
  { id: 'p_061', name: 'Jaylen Waddle', position: 'WR', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA', touchdowns: 9, passYards: 0, rushYards: 31, recYards: 1285 },
  { id: 'p_062', name: 'Tank Dell', position: 'WR', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU', touchdowns: 7, passYards: 0, rushYards: 18, recYards: 871 },
  { id: 'p_063', name: 'Marvin Harrison Jr.', position: 'WR', nflTeam: 'Arizona Cardinals', nflTeamAbbr: 'ARI', touchdowns: 11, passYards: 0, rushYards: 24, recYards: 1351 },
  { id: 'p_064', name: 'Rome Odunze', position: 'WR', nflTeam: 'Chicago Bears', nflTeamAbbr: 'CHI', touchdowns: 7, passYards: 0, rushYards: 16, recYards: 908 },
  { id: 'p_065', name: 'Xavier Legette', position: 'WR', nflTeam: 'Carolina Panthers', nflTeamAbbr: 'CAR', touchdowns: 6, passYards: 0, rushYards: 11, recYards: 718 },

  // TEs (~12)
  { id: 'p_066', name: 'Travis Kelce', position: 'TE', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC', touchdowns: 11, passYards: 0, rushYards: 0, recYards: 984 },
  { id: 'p_067', name: 'Sam LaPorta', position: 'TE', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET', touchdowns: 7, passYards: 0, rushYards: 0, recYards: 822 },
  { id: 'p_068', name: 'Trey McBride', position: 'TE', nflTeam: 'Arizona Cardinals', nflTeamAbbr: 'ARI', touchdowns: 5, passYards: 0, rushYards: 0, recYards: 825 },
  { id: 'p_069', name: 'Dalton Kincaid', position: 'TE', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF', touchdowns: 4, passYards: 0, rushYards: 0, recYards: 673 },
  { id: 'p_070', name: 'Jake Ferguson', position: 'TE', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL', touchdowns: 6, passYards: 0, rushYards: 0, recYards: 761 },
  { id: 'p_071', name: 'Mark Andrews', position: 'TE', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL', touchdowns: 9, passYards: 0, rushYards: 0, recYards: 847 },
  { id: 'p_072', name: 'T.J. Hockenson', position: 'TE', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN', touchdowns: 8, passYards: 0, rushYards: 0, recYards: 718 },
  { id: 'p_073', name: 'Kyle Pitts', position: 'TE', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL', touchdowns: 6, passYards: 0, rushYards: 0, recYards: 902 },
  { id: 'p_074', name: 'Evan Engram', position: 'TE', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX', touchdowns: 5, passYards: 0, rushYards: 0, recYards: 776 },
  { id: 'p_075', name: 'Cade Otton', position: 'TE', nflTeam: 'Tampa Bay Buccaneers', nflTeamAbbr: 'TB', touchdowns: 4, passYards: 0, rushYards: 0, recYards: 512 },
  { id: 'p_076', name: 'Tucker Kraft', position: 'TE', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB', touchdowns: 5, passYards: 0, rushYards: 0, recYards: 487 },
  { id: 'p_077', name: 'Isaiah Likely', position: 'TE', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL', touchdowns: 4, passYards: 0, rushYards: 0, recYards: 431 },

  // Ks (~10)
  { id: 'p_078', name: 'Justin Tucker', position: 'K', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_079', name: 'Harrison Butker', position: 'K', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_080', name: 'Evan McPherson', position: 'K', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_081', name: 'Tyler Bass', position: 'K', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_082', name: 'Jake Elliott', position: 'K', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_083', name: 'Daniel Carlson', position: 'K', nflTeam: 'Las Vegas Raiders', nflTeamAbbr: 'LV', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_084', name: 'Cameron Dicker', position: 'K', nflTeam: 'Los Angeles Chargers', nflTeamAbbr: 'LAC', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_085', name: 'Younghoe Koo', position: 'K', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_086', name: 'Greg Joseph', position: 'K', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },
  { id: "p_087", name: "Ka'imi Fairbairn", position: 'K', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU', touchdowns: 0, passYards: 0, rushYards: 0, recYards: 0 },

  // DEFs (~13)
  { id: 'p_088', name: 'San Francisco 49ers', position: 'DEF', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF', touchdowns: 4, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_089', name: 'Dallas Cowboys', position: 'DEF', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL', touchdowns: 3, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_090', name: 'Baltimore Ravens', position: 'DEF', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL', touchdowns: 4, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_091', name: 'Philadelphia Eagles', position: 'DEF', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI', touchdowns: 3, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_092', name: 'Pittsburgh Steelers', position: 'DEF', nflTeam: 'Pittsburgh Steelers', nflTeamAbbr: 'PIT', touchdowns: 2, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_093', name: 'Kansas City Chiefs', position: 'DEF', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC', touchdowns: 2, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_094', name: 'Buffalo Bills', position: 'DEF', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF', touchdowns: 3, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_095', name: 'Cleveland Browns', position: 'DEF', nflTeam: 'Cleveland Browns', nflTeamAbbr: 'CLE', touchdowns: 2, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_096', name: 'Detroit Lions', position: 'DEF', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET', touchdowns: 3, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_097', name: 'New York Jets', position: 'DEF', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ', touchdowns: 2, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_098', name: 'Cincinnati Bengals', position: 'DEF', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN', touchdowns: 1, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_099', name: 'Miami Dolphins', position: 'DEF', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA', touchdowns: 2, passYards: 0, rushYards: 0, recYards: 0 },
  { id: 'p_100', name: 'Houston Texans', position: 'DEF', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU', touchdowns: 3, passYards: 0, rushYards: 0, recYards: 0 },
];

export const MOCK_TEAMS = [
  { id: 'team_1',  name: 'Gridiron Ghosts',    initials: 'GG' },
  { id: 'team_2',  name: 'Blitz Brigade',       initials: 'BB' },
  { id: 'team_3',  name: 'End Zone Elites',     initials: 'EZ' },
  { id: 'team_4',  name: 'Red Zone Rockets',    initials: 'RZ' },
  { id: 'team_5',  name: 'Hail Mary Heroes',    initials: 'HM' },
  { id: 'team_6',  name: 'Fourth Down Force',   initials: 'FF' },
  { id: 'team_7',  name: 'Punt Return Pros',    initials: 'PP' },
  { id: 'team_8',  name: 'Two-Point Titans',    initials: 'TT' },
  { id: 'team_9',  name: 'Sack Attack Squad',   initials: 'SA' },
  { id: 'team_10', name: 'Pocket Passers',      initials: 'PO' },
  { id: 'team_11', name: 'Deep Ball Dynasty',   initials: 'DB' },
  { id: 'team_12', name: 'Scramble Kings',      initials: 'SK' },
];
