// Mock data for the Draft Room feature.
// MOCK_PLAYERS: ~100 NFL players across 6 positions and 12 NFL teams.
// MOCK_TEAMS: 12 fantasy teams with id, name, and initials.

export const MOCK_PLAYERS = [
  // QBs (~15)
  { id: 'p_001', name: 'Patrick Mahomes', position: 'QB', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC' },
  { id: 'p_002', name: 'Josh Allen', position: 'QB', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF' },
  { id: 'p_003', name: 'Lamar Jackson', position: 'QB', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL' },
  { id: 'p_004', name: 'Joe Burrow', position: 'QB', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN' },
  { id: 'p_005', name: 'Jalen Hurts', position: 'QB', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI' },
  { id: 'p_006', name: 'Tua Tagovailoa', position: 'QB', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA' },
  { id: 'p_007', name: 'Dak Prescott', position: 'QB', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL' },
  { id: 'p_008', name: 'Justin Herbert', position: 'QB', nflTeam: 'Los Angeles Chargers', nflTeamAbbr: 'LAC' },
  { id: 'p_009', name: 'Trevor Lawrence', position: 'QB', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX' },
  { id: 'p_010', name: 'Anthony Richardson', position: 'QB', nflTeam: 'Indianapolis Colts', nflTeamAbbr: 'IND' },
  { id: 'p_011', name: 'Sam Darnold', position: 'QB', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN' },
  { id: 'p_012', name: 'Jordan Love', position: 'QB', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB' },
  { id: 'p_013', name: 'C.J. Stroud', position: 'QB', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU' },
  { id: 'p_014', name: 'Caleb Williams', position: 'QB', nflTeam: 'Chicago Bears', nflTeamAbbr: 'CHI' },
  { id: 'p_015', name: 'Jayden Daniels', position: 'QB', nflTeam: 'Washington Commanders', nflTeamAbbr: 'WAS' },

  // RBs (~22)
  { id: 'p_016', name: 'Christian McCaffrey', position: 'RB', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF' },
  { id: 'p_017', name: 'Saquon Barkley', position: 'RB', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI' },
  { id: 'p_018', name: 'Derrick Henry', position: 'RB', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL' },
  { id: 'p_019', name: 'Josh Jacobs', position: 'RB', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB' },
  { id: 'p_020', name: 'Tony Pollard', position: 'RB', nflTeam: 'Tennessee Titans', nflTeamAbbr: 'TEN' },
  { id: 'p_021', name: 'Rhamondre Stevenson', position: 'RB', nflTeam: 'New England Patriots', nflTeamAbbr: 'NE' },
  { id: 'p_022', name: 'Travis Etienne', position: 'RB', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX' },
  { id: 'p_023', name: 'Jonathan Taylor', position: 'RB', nflTeam: 'Indianapolis Colts', nflTeamAbbr: 'IND' },
  { id: 'p_024', name: 'De\'Von Achane', position: 'RB', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA' },
  { id: 'p_025', name: 'Isiah Pacheco', position: 'RB', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC' },
  { id: 'p_026', name: 'Brian Robinson Jr.', position: 'RB', nflTeam: 'Washington Commanders', nflTeamAbbr: 'WAS' },
  { id: 'p_027', name: 'Jahmyr Gibbs', position: 'RB', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET' },
  { id: 'p_028', name: 'David Montgomery', position: 'RB', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET' },
  { id: 'p_029', name: 'Kyren Williams', position: 'RB', nflTeam: 'Los Angeles Rams', nflTeamAbbr: 'LAR' },
  { id: 'p_030', name: 'Aaron Jones', position: 'RB', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN' },
  { id: 'p_031', name: 'James Cook', position: 'RB', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF' },
  { id: 'p_032', name: 'Breece Hall', position: 'RB', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ' },
  { id: 'p_033', name: 'Najee Harris', position: 'RB', nflTeam: 'Pittsburgh Steelers', nflTeamAbbr: 'PIT' },
  { id: 'p_034', name: 'Joe Mixon', position: 'RB', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU' },
  { id: 'p_035', name: 'Alvin Kamara', position: 'RB', nflTeam: 'New Orleans Saints', nflTeamAbbr: 'NO' },
  { id: 'p_036', name: 'Nick Chubb', position: 'RB', nflTeam: 'Cleveland Browns', nflTeamAbbr: 'CLE' },
  { id: 'p_037', name: 'Bijan Robinson', position: 'RB', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL' },

  // WRs (~28)
  { id: 'p_038', name: 'Tyreek Hill', position: 'WR', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA' },
  { id: 'p_039', name: 'Justin Jefferson', position: 'WR', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN' },
  { id: 'p_040', name: 'CeeDee Lamb', position: 'WR', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL' },
  { id: 'p_041', name: 'Davante Adams', position: 'WR', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ' },
  { id: 'p_042', name: 'Stefon Diggs', position: 'WR', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU' },
  { id: 'p_043', name: 'A.J. Brown', position: 'WR', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI' },
  { id: 'p_044', name: 'Ja\'Marr Chase', position: 'WR', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN' },
  { id: 'p_045', name: 'DeVonta Smith', position: 'WR', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI' },
  { id: 'p_046', name: 'Amon-Ra St. Brown', position: 'WR', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET' },
  { id: 'p_047', name: 'Puka Nacua', position: 'WR', nflTeam: 'Los Angeles Rams', nflTeamAbbr: 'LAR' },
  { id: 'p_048', name: 'Keenan Allen', position: 'WR', nflTeam: 'Chicago Bears', nflTeamAbbr: 'CHI' },
  { id: 'p_049', name: 'Tee Higgins', position: 'WR', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN' },
  { id: 'p_050', name: 'Mike Evans', position: 'WR', nflTeam: 'Tampa Bay Buccaneers', nflTeamAbbr: 'TB' },
  { id: 'p_051', name: 'Chris Olave', position: 'WR', nflTeam: 'New Orleans Saints', nflTeamAbbr: 'NO' },
  { id: 'p_052', name: 'Deebo Samuel', position: 'WR', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF' },
  { id: 'p_053', name: 'Brandon Aiyuk', position: 'WR', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF' },
  { id: 'p_054', name: 'Christian Watson', position: 'WR', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB' },
  { id: 'p_055', name: 'Garrett Wilson', position: 'WR', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ' },
  { id: 'p_056', name: 'Rashee Rice', position: 'WR', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC' },
  { id: 'p_057', name: 'Drake London', position: 'WR', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL' },
  { id: 'p_058', name: 'Zay Jones', position: 'WR', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX' },
  { id: 'p_059', name: 'Courtland Sutton', position: 'WR', nflTeam: 'Denver Broncos', nflTeamAbbr: 'DEN' },
  { id: 'p_060', name: 'Diontae Johnson', position: 'WR', nflTeam: 'Carolina Panthers', nflTeamAbbr: 'CAR' },
  { id: 'p_061', name: 'Jaylen Waddle', position: 'WR', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA' },
  { id: 'p_062', name: 'Tank Dell', position: 'WR', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU' },
  { id: 'p_063', name: 'Marvin Harrison Jr.', position: 'WR', nflTeam: 'Arizona Cardinals', nflTeamAbbr: 'ARI' },
  { id: 'p_064', name: 'Rome Odunze', position: 'WR', nflTeam: 'Chicago Bears', nflTeamAbbr: 'CHI' },
  { id: 'p_065', name: 'Xavier Legette', position: 'WR', nflTeam: 'Carolina Panthers', nflTeamAbbr: 'CAR' },

  // TEs (~12)
  { id: 'p_066', name: 'Travis Kelce', position: 'TE', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC' },
  { id: 'p_067', name: 'Sam LaPorta', position: 'TE', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET' },
  { id: 'p_068', name: 'Trey McBride', position: 'TE', nflTeam: 'Arizona Cardinals', nflTeamAbbr: 'ARI' },
  { id: 'p_069', name: 'Dalton Kincaid', position: 'TE', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF' },
  { id: 'p_070', name: 'Jake Ferguson', position: 'TE', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL' },
  { id: 'p_071', name: 'Mark Andrews', position: 'TE', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL' },
  { id: 'p_072', name: 'T.J. Hockenson', position: 'TE', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN' },
  { id: 'p_073', name: 'Kyle Pitts', position: 'TE', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL' },
  { id: 'p_074', name: 'Evan Engram', position: 'TE', nflTeam: 'Jacksonville Jaguars', nflTeamAbbr: 'JAX' },
  { id: 'p_075', name: 'Cade Otton', position: 'TE', nflTeam: 'Tampa Bay Buccaneers', nflTeamAbbr: 'TB' },
  { id: 'p_076', name: 'Tucker Kraft', position: 'TE', nflTeam: 'Green Bay Packers', nflTeamAbbr: 'GB' },
  { id: 'p_077', name: 'Isaiah Likely', position: 'TE', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL' },

  // Ks (~10)
  { id: 'p_078', name: 'Justin Tucker', position: 'K', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL' },
  { id: 'p_079', name: 'Harrison Butker', position: 'K', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC' },
  { id: 'p_080', name: 'Evan McPherson', position: 'K', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN' },
  { id: 'p_081', name: 'Tyler Bass', position: 'K', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF' },
  { id: 'p_082', name: 'Jake Elliott', position: 'K', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI' },
  { id: 'p_083', name: 'Daniel Carlson', position: 'K', nflTeam: 'Las Vegas Raiders', nflTeamAbbr: 'LV' },
  { id: 'p_084', name: 'Cameron Dicker', position: 'K', nflTeam: 'Los Angeles Chargers', nflTeamAbbr: 'LAC' },
  { id: 'p_085', name: 'Younghoe Koo', position: 'K', nflTeam: 'Atlanta Falcons', nflTeamAbbr: 'ATL' },
  { id: 'p_086', name: 'Greg Joseph', position: 'K', nflTeam: 'Minnesota Vikings', nflTeamAbbr: 'MIN' },
  { id: 'p_087', name: 'Ka\'imi Fairbairn', position: 'K', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU' },

  // DEFs (~13)
  { id: 'p_088', name: 'San Francisco 49ers', position: 'DEF', nflTeam: 'San Francisco 49ers', nflTeamAbbr: 'SF' },
  { id: 'p_089', name: 'Dallas Cowboys', position: 'DEF', nflTeam: 'Dallas Cowboys', nflTeamAbbr: 'DAL' },
  { id: 'p_090', name: 'Baltimore Ravens', position: 'DEF', nflTeam: 'Baltimore Ravens', nflTeamAbbr: 'BAL' },
  { id: 'p_091', name: 'Philadelphia Eagles', position: 'DEF', nflTeam: 'Philadelphia Eagles', nflTeamAbbr: 'PHI' },
  { id: 'p_092', name: 'Pittsburgh Steelers', position: 'DEF', nflTeam: 'Pittsburgh Steelers', nflTeamAbbr: 'PIT' },
  { id: 'p_093', name: 'Kansas City Chiefs', position: 'DEF', nflTeam: 'Kansas City Chiefs', nflTeamAbbr: 'KC' },
  { id: 'p_094', name: 'Buffalo Bills', position: 'DEF', nflTeam: 'Buffalo Bills', nflTeamAbbr: 'BUF' },
  { id: 'p_095', name: 'Cleveland Browns', position: 'DEF', nflTeam: 'Cleveland Browns', nflTeamAbbr: 'CLE' },
  { id: 'p_096', name: 'Detroit Lions', position: 'DEF', nflTeam: 'Detroit Lions', nflTeamAbbr: 'DET' },
  { id: 'p_097', name: 'New York Jets', position: 'DEF', nflTeam: 'New York Jets', nflTeamAbbr: 'NYJ' },
  { id: 'p_098', name: 'Cincinnati Bengals', position: 'DEF', nflTeam: 'Cincinnati Bengals', nflTeamAbbr: 'CIN' },
  { id: 'p_099', name: 'Miami Dolphins', position: 'DEF', nflTeam: 'Miami Dolphins', nflTeamAbbr: 'MIA' },
  { id: 'p_100', name: 'Houston Texans', position: 'DEF', nflTeam: 'Houston Texans', nflTeamAbbr: 'HOU' },
];

export const MOCK_TEAMS = [
  { id: 'team_1',  name: 'Gridiron Ghosts',    initials: 'GG' },
  { id: 'team_2',  name: 'Blitz Brigade',       initials: 'BB' },
  { id: 'team_3',  name: 'End Zone Elites',     initials: 'EZ' },
  { id: 'team_4',  name: 'Red Zone Rockets',    initials: 'RZ' },
  { id: 'team_5',  name: 'Hail Mary Heroes',    initials: 'HM' },
  { id: 'team_6',  name: 'Fourth Down Force',   initials: 'FF' },
  { id: 'team_7',  name: 'Punt Return Pros',    initials: 'PP' },
  { id: 'team_8',  name: 'Two-Point Titans',    initials: 'TT' },
  { id: 'team_9',  name: 'Sack Attack Squad',   initials: 'SA' },
  { id: 'team_10', name: 'Pocket Passers',      initials: 'PO' },
  { id: 'team_11', name: 'Deep Ball Dynasty',   initials: 'DB' },
  { id: 'team_12', name: 'Scramble Kings',      initials: 'SK' },
];
